services:
  ms-alerta-incendios:
    build: ./ms-alerta-incendios
    container_name: ms-alerta-incendios-container
    ports:
      - "8081:8081"
      
    volumes:
      # Montamos tu carpeta de la Wallet en la ruta /app/wallet del contenedor
      - ./Wallet_ms-alerta-incendio:/app/wallet
    environment:
      # Esta variable le dirá a tu application.yml dónde buscar las llaves
      - TNS_ADMIN_DIR=/app/wallet


  ms-monitoreo-geo:
    build: ./ms-monitoreo-geo
    container_name: ms-monitoreo-geo-container
    ports:
      - "8082:8082" 
    volumes:
      - ./Wallet_ms-alerta-incendio:/app/wallet  
    environment:
      - TNS_ADMIN_DIR=/app/wallet