server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      # Permisos para que React (Vite) pueda entrar
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173" # <-- Cambia esto si tu front corre en otro puerto
            allowedMethods: "*"
            allowedHeaders: "*"
      
      routes:
        - id: alerta-route
          uri: ${MS_ALERTA_URL:http://localhost:8081}
          predicates:
            - Path=/api/reportes/**

        - id: monitoreo-route
          uri: ${MS_MONITOREO_URL:http://localhost:8082}
          predicates:
            - Path=/api/mapa/**

        - id: notificaciones-route
          uri: ${MS_NOTIFICACIONES_URL:http://localhost:8083}
          predicates:
            - Path=/api/notificaciones/**