server:
  port: 8082

spring:
  application:
    name: ms-monitoreo
  datasource:
    url: jdbc:oracle:thin:@fxvgr0rd9mqxj20w_high?TNS_ADMIN=C:/Fullstack/Wallet_FXVGR0RD9MQXJ20W
    username: ADMIN
    password: Matiasneira123.
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

alerta:
  url: http://localhost:8081

resilience4j:
  circuitbreaker:
    instances:
      alertaCB:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3